/*
 * sport-restful-backend
 * Sport App Backend For Android Course
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ResponseStatuses
 */
@JsonAdapter(ResponseStatuses.Adapter.class)
public enum ResponseStatuses {
  
  SUCCESS("success"),
  
  FAIL("fail"),
  
  ERROR("error");

  private String value;

  ResponseStatuses(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ResponseStatuses fromValue(String text) {
    for (ResponseStatuses b : ResponseStatuses.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ResponseStatuses> {
    @Override
    public void write(final JsonWriter jsonWriter, final ResponseStatuses enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ResponseStatuses read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ResponseStatuses.fromValue(String.valueOf(value));
    }
  }
}

