/*
 * sport-restful-backend
 * Sport App Backend For Android Course
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ResponseErrorCodes
 */
@JsonAdapter(ResponseErrorCodes.Adapter.class)
public enum ResponseErrorCodes {
  
  INTERNAL_ERROR("INTERNAL_ERROR"),
  
  UNKNOWN_ERROR("UNKNOWN_ERROR");

  private String value;

  ResponseErrorCodes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ResponseErrorCodes fromValue(String text) {
    for (ResponseErrorCodes b : ResponseErrorCodes.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ResponseErrorCodes> {
    @Override
    public void write(final JsonWriter jsonWriter, final ResponseErrorCodes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ResponseErrorCodes read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ResponseErrorCodes.fromValue(String.valueOf(value));
    }
  }
}

